### ISSUE TITLE
yara.py object has no attribute

### ISSUE THREAD

**Issue by ITmustang** [0xdea/ghidra-scripts#3]
Traceback (most recent call last):
  File "ghidra_scripts/yara.py", line 53, in <module>
    add_bookmark_comment(vaddr, current_rule)
  File "ghidra_scripts/yara.py", line 30, in add_bookmark_comment
    cu.setComment(CodeUnit.EOL_COMMENT, text)
AttributeError: 'NoneType' object has no attribute 'setComment'

**Comment by ITmustang** [comment]
N/A wrong submission, apologies
